config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_closed', on: :member
  end
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :memberships do
    post 'toggle_confirmed', on: :member
  end

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only: [:index, :show]
  post 'places', to:'places#search'

  root 'breweries#index'

  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships, -> { where confirmed: true }
  has_many :members, through: :memberships, source: :user
  has_many :applications, -> { where confirmed: [nil, false] }, class_name: "Membership"
  has_many :applicants, through: :applications, source: :user

  # scope :membership, -> { where confirmed: true}
  # scope :application, -> { where confirmed: [nil, false] }

  def self.top(how_many)
    sorted_by_rating_in_desc_order = all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_in_desc_order[0, how_many]
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :current_user_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when 'name' then @beer_clubs.sort_by(&:name)
                  when 'founded' then @beer_clubs.sort_by(&:founded)
                  when 'city' then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = if @beer_club.members.include? current_user
                    @beer_club.memberships.where(user: current_user).first
                  else
                    Membership.new beer_club: @beer_club
                  end
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        Membership.create beer_club_id: @beer_club.id, user_id: current_user.id, confirmed: true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club, local: true) do |form| %>
  <% if beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="name" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
     <%= form.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="founded" class="col-sm-2 col-form-label">Founded</label>
    <div class="col-sm-10">
      <%= form.number_field :founded, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="city" class="col-sm-2 col-form-label">City</label>
    <div class="col-sm-10">
     <%= form.text_field :city, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class:'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Show', @beer_club, class:"btn btn-primary" %>
<%= link_to 'Back', beer_clubs_path, class:"btn btn-secondary" %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', beer_clubs_path(order:"name") %> </th>
      <th> <%= link_to 'Founded', beer_clubs_path(order:"founded") %> </th>
      <th> <%= link_to 'City', beer_clubs_path(order:"city") %> </th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer Club', new_beer_club_path, class:"btn btn-primary" %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form', beer_club: @beer_club %>

<%= link_to 'Back', beer_clubs_path, class:"btn btn-secondary" %>

app/views/beer_clubs/show.html.erb
<h2>
  <%= @beer_club.name %> <%= @beer_club.city %>
</h2>

<p>
 Founded
  <%= @beer_club.founded %>
</p>

<h3>Members</h3>

<ul>
  <% @beer_club.members.each do |member| %>
    <li><%= link_to member.username, member %></li>
  <% end %>
</ul>

<h3>Member requests</h3>

<ul>
  <% @beer_club.applicants.each do |applicant| %>
    <li><%= link_to applicant.username, applicant %>
    <% if @beer_club.members.include?(current_user) %>
      <%= link_to "confirm membership", toggle_confirmed_membership_path(applicant.id), method: :post, class: "btn btn-success" %>
    <% end %>
    </li>
  <% end %>
</ul>

<% if current_user %>

  <% if @beer_club.members.exclude?(current_user) && @beer_club.applicants.exclude?(current_user) %>
    <%= form_for(@membership) do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value: "Apply for a membership", class:"btn btn-primary"  %>
    <% end %>
  <% elsif  @beer_club.members.include?(current_user)%>
    <%= form_for(@membership, method: "delete") do |f| %>
      <%= f.hidden_field :beer_club_id %>
      <%= f.submit value: "end the membership", class:"btn btn-danger" %>
    <% end %>
  <% end %>

  <br>
  <%= link_to 'Edit', edit_beer_club_path(@beer_club), class:"btn btn-warning" %> 
  <br>
  <%= link_to 'Destroy', @beer_club, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<% end %>